### ISSUE TITLE
No funding information

### ISSUE THREAD

**Issue by ukmaker** [tioluigidev/Tio-Luigis-Components-Codification-Guide#1]
This is so useful I want to send you some money. How can I do that?

**Comment by luizferreira-io** [comment]
Hello, ukmaker. Thank you very much for your feedback! I'm glad this ebook helped you.

I have configured sponsor settings in this repository, but I don't know why the sponsor button does not appear in the repository page. Maybe because Git Hub has some issues with large binary files. I am planning to eliminate iBooks version and make a new and smaller PDF version.

However, you can find the Sponsor link in my home Git Hub page:
https://github.com/tioluigidev

Or directly:
https://github.com/sponsors/tioluigidev

Thank you,
Luiz "Tio Luigi" Ferreira
